### ISSUE TITLE
why mix scripts

### ISSUE THREAD

**Issue by lshems** [zenuavsolutions/Horus-Mavlink-Telemetry#4]
Why do you use mix scripts? You could do the same thing in the widget background. 

Would be much easier to install (only main.lua!), no compile options neccesary, etc.

??

**Comment by n9rai** [comment]
this was a test because of the high latency, i have also a version where i read passthrough inside widget

**Comment by lshems** [comment]
Ok, if I understand correctly, this script displays telemetry values received by sport.

You will never need to get data any faster than screen updates.

What makes you believe there is a latency problem. How does it show.

**Comment by lshems** [comment]
I read you get sensor lost messages. They have as far as I know nothing to do with your Lua scripts. Even not installing the scripts will probably give the same errors.

Or do you get the sensor lost messages from your script?

**Comment by lshems** [comment]
The argument of havin them available as telemetry values isn't valid as well. Even in the background of the script you could update the telemetry values to have them available to others.

I personally would noot use mixer scripts unless really really neccesary, since it asks for a compile option. 

But of course it's all up to you :)
