### ISSUE TITLE
global function widget()

### ISSUE THREAD

**Issue by lshems** [zenuavsolutions/Horus-Mavlink-Telemetry#5]
why did you make the function widget() global??

will cause problems when running mutiplle instances.

**Comment by n9rai** [comment]
yes you are wright! I fixed this local but forgot to commit

**Comment by lshems** [comment]
There are a lot of other functions missing the local. There should not be anything global for a widget.

**Comment by n9rai** [comment]
fixed with last commit, thank you for your help!
